pull_request_rules:
  - name: Make sure PR are update before merging with rebase
    description: This automatically rebases PRs when they are out-of-date with the
      base branch to avoid semantic conflicts (next step us switch to merge
      queue).
    conditions:
      - "#commits-behind >= 10"
    actions:
      rebase:
  - name: Add a queue label when PR is queued
    description: Toggle the queue label when a pull request is (un)queued.
    conditions:
      - queue-position > 0
    actions:
      label:
        toggle:
          - merge-queued
  - name: Request review from team
    description: Request review from a specific team when checks are green.
    conditions:
      - -closed
      - "#approved-reviews-by = 0"
      - "#changes-requested-reviews-by = 0"
      - review-requested != @TEAM_NAME_HERE
    actions:
      request_reviews:
        teams:
          - TEAM_NAME_HERE
  - name: Label first PR of Mergify Stacks PRs
    description: The first PR of a Mergify stack should be labeled as such
    conditions:
      - "commits[0].commit_message ~= (?m)Change-Id:"
      - -base ~= ^mergify_cli/
    actions:
      label:
        toggle:
          - top of the stack
  - name: Assign t-shirt size to PR
    description: Assign a t-shirt size label to a pull request based on the number
      of lines changed.
    conditions:
      - "#modified-lines >= 100"
      - "#modified-lines < 500"
    actions:
      label:
        toggle:
          - size/L
  - name: Automatic merge during office hours + hotfix support
    description: Merge when PR passes all branch protection during office hours,
      except for hotfix
    conditions:
      - or:
          - schedule = Mon-Fri 09:00-17:00[America/Los_Angeles]
          - label = hotfix
    actions:
      merge:
