name: Deploy BoomPass to Vercel

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name

  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Checkout repository
        uses: actions/checkout@v4

      - name: 📦 Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Ensure this matches your project requirements
          cache: 'npm'

      - name: 📂 Install dependencies
        run: npm install
        working-directory: BoomPass  # Adjust this if your project is in a subdirectory

      - name: 🔨 Build project
        run: npm run build
        working-directory: BoomPass  # Adjust this if needed

      - name: 🚀 Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Store in GitHub Secrets
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  # Store in GitHub Secrets
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # Store in GitHub Secrets
          working-directory: BoomPass  # Adjust this if your project is in a subdirectory
